### ISSUE TITLE
bug report: Sc-im segmentation fault on save

### ISSUE THREAD

**Issue by buribu** [its-pointless/its-pointless.github.io#4] opened 2017-12-24 02:11 UTC
scim fails and terminates the application with segmentation fault when trying to save a file.

**Comment by its-pointless** [comment] 2017-12-24 07:14
I updated to version 7 and couldn't replicate issue. See if new version is fixed.

**Comment by buribu** [comment] 2017-12-24 16:36
I upgraded to version 7. :) I used 2 devices. I got the same result. It does not save and does not load. : | Segmentation fault only


![screenshot_20171224-142034](https://user-images.githubusercontent.com/782908/34327886-7ee55b52-e8b7-11e7-80ff-1bbfa54de2d4.png)

![screenshot_20171224-142703](https://user-images.githubusercontent.com/782908/34327885-74d86dde-e8b7-11e7-9833-d86a76e68d0f.png)

![screenshot_20171224-112720](https://user-images.githubusercontent.com/782908/34327881-6b167bce-e8b7-11e7-8e5b-200a934fbbcf.png)

![screenshot_20171224-141744](https://user-images.githubusercontent.com/782908/34327880-64153b8a-e8b7-11e7-8f39-06cd73ac4f0b.png)

**Comment by its-pointless** [comment] 2017-12-24 20:10
so arm?
It could be -Oz bug. I will get around to it shortly.

**Comment by its-pointless** [comment] 2017-12-25 05:25
I can't reproduce it ...
tried on 2 arm devices.

**Comment by buribu** [comment] 2017-12-28 21:11
Really? I already tested on other arm devices later and got the same segfault.
Did you try to save the worksheet with ":w filename.sc"?
Did you try to load the worksheet with ":load filename.sc"?
And did you succeed in version 0.7.0?

What's the magic?

In version 0.3.0 I was able to do ":w filename.sc" . But  ":load filename.sc" never worked.

I could load using the file as parameter "$scim filename.sc"

In version 0.7.0 none of this works for me.

In file.c there is a lib that is incompatible with bionic called <wordexp.h> I think it may have been this.

**Comment by its-pointless** [comment] 2017-12-29 22:17
I integrated wordexp.c and wordexp.h from musl c (which is where most libandroid-support stuff is from). This leaves a few problems. If its arm only it could be a lib from official tree that needs to recompiled because of -Oz compiling for arm causes weird issues ajd my testing libs are different. It could be integrating musl wordexp.c is incompatible with certain android  rom versions and not others.   it could be permissions missing .. have you executed termux-storage-setup ?

**Comment by buribu** [comment] 2017-12-29 23:02
Yes. I ran termux-setup-storage on all devices before testing ... I got the same Segfault on every device. What is your device?

**Comment by its-pointless** [comment] 2017-12-29 23:06
2 devices i tested it on. A samsung s4. Its running a custom aosp rom though. Other arm device is a sony android tv running android 6.

**Comment by its-pointless** [comment] 2017-12-29 23:24
k iv reproduced it. its one of the libs in termux proper.

**Comment by its-pointless** [comment] 2017-12-30 00:11
should be fixed now.

**Comment by buribu** [comment] 2017-12-30 01:40
This problem was apparently solved by the package maintainer.

**Comment by buribu** [comment] 2017-12-30 01:41
Now everything seems to work. Thank you very much.

**Closed** 2017-12-30 08:06 UTC
